const REQUIRED_ENV = ["SUPABASE_URL", "SUPABASE_ANON_KEY", "SUPABASE_SERVICE_ROLE_KEY"];
const ADMIN_ROLES = new Set(["admin", "super_admin"]);
function json(res, status, data) { return res.status(status).json(data); }
function hasDb() { return REQUIRED_ENV.every((key) => process.env[key]); }
function restUrl(table, query = "") { return `${process.env.SUPABASE_URL}/rest/v1/${table}${query}`; }
function authUrl(path) { return `${process.env.SUPABASE_URL}/auth/v1/${path}`; }
function serviceHeaders(extra = {}) { return { apikey: process.env.SUPABASE_SERVICE_ROLE_KEY, Authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`, "Content-Type": "application/json", Prefer: "return=representation", ...extra }; }
function anonHeaders(extra = {}) { return { apikey: process.env.SUPABASE_ANON_KEY, "Content-Type": "application/json", ...extra }; }
async function supabaseJson(url, init = {}) { const response = await fetch(url, init); const text = await response.text(); let body = null; try { body = text ? JSON.parse(text) : null; } catch { body = text; } if (!response.ok) throw new Error(body?.error_description || body?.message || body?.hint || body?.details || "Supabase 请求失败"); return body; }
async function parseBody(req) { if (req.body && typeof req.body === "object") return req.body; const chunks = []; for await (const chunk of req) chunks.push(chunk); try { return JSON.parse(Buffer.concat(chunks).toString("utf8") || "{}"); } catch { return {}; } }
function tokenFrom(req) { return String(req.headers.authorization || req.headers["x-mcj-access-token"] || req.headers["x-mcj-service-token"] || "").replace(/^Bearer\s+/i, "").trim(); }
async function roleFromToken(token) { const user = await supabaseJson(authUrl("user"), { headers: anonHeaders({ Authorization: `Bearer ${token}` }) }); const rows = await supabaseJson(restUrl("profiles", `?id=eq.${encodeURIComponent(user.id)}&limit=1`), { headers: serviceHeaders() }); return rows[0] || null; }
async function requireActor(req) { const token = tokenFrom(req); if (!token) throw Object.assign(new Error("请先登录。"), { status: 401 }); const profile = await roleFromToken(token); if (!profile || profile.status !== "active") throw Object.assign(new Error("账号无效或已停用。"), { status: 403 }); return profile; }
function canReview(profile) { return ADMIN_ROLES.has(profile.role); }
export default async function handler(req, res) { if (!hasDb()) return json(res, req.method === "GET" ? 200 : 503, { ok: req.method === "GET", configured: false, reports: [], message: "未配置 Supabase，工资报备不返回假数据。" }); try { const actor = await requireActor(req); if (req.method === "GET") { const query = ADMIN_ROLES.has(actor.role) ? "?order=created_at.desc&limit=300" : `?customer_service_id=eq.${encodeURIComponent(actor.id)}&order=created_at.desc&limit=100`; const reports = await supabaseJson(restUrl("customer_service_reports", query), { headers: serviceHeaders() }); return json(res, 200, { ok: true, configured: true, reports: Array.isArray(reports) ? reports : [] }); }
    if (req.method !== "POST") return json(res, 405, { ok: false, message: "Method Not Allowed" }); const body = await parseBody(req); if (body.action === "submit") { if (actor.role !== "customer_service") return json(res, 403, { ok: false, message: "只有客服可以提交工资报备。" }); const rows = await supabaseJson(restUrl("customer_service_reports"), { method: "POST", headers: serviceHeaders(), body: JSON.stringify({ customer_service_id: actor.id, report_date: body.report_date || new Date().toISOString().slice(0, 10), shift_start: body.shift_start || "", shift_end: body.shift_end || "", orders_handled: Number(body.orders_handled || 0), salary_amount: Number(body.salary_amount || 0), note: String(body.note || ""), status: "pending", created_at: new Date().toISOString() }) }); return json(res, 200, { ok: true, message: "工资报备已提交。", report: rows[0] || null }); }
    if (!canReview(actor)) return json(res, 403, { ok: false, message: "没有工资报备审核权限。" }); const id = String(body.id || ""); const status = String(body.status || ""); if (!id || !["approved", "rejected", "paid"].includes(status)) return json(res, 400, { ok: false, message: "工资报备审核参数无效。" }); const rows = await supabaseJson(restUrl("customer_service_reports", `?id=eq.${encodeURIComponent(id)}`), { method: "PATCH", headers: serviceHeaders(), body: JSON.stringify({ status, admin_note: String(body.admin_note || body.adminNote || ""), reviewed_at: new Date().toISOString() }) }); return json(res, 200, { ok: true, message: "工资报备状态已更新。", report: rows[0] || null }); } catch (error) { return json(res, error.status || 500, { ok: false, message: error.message || "工资报备接口异常。" }); } }
