import crypto from "node:crypto";
const REQUIRED_ENV = ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"];
const SERVICE_ROLES = new Set(["customer_service", "service", "super_admin"]);
const ORDER_STATUSES = ["待支付", "待接单", "待老板确认", "待开始", "进行中", "待确认完成", "已完成", "已取消", "售后处理中", "退款处理中", "已退款", "异常订单"];
const PAY_STATUSES = ["未支付", "支付中", "已支付", "支付失败", "部分退款", "已退款"];
function json(res,status,data){res.status(status).json(data)}
function hasDb(){return REQUIRED_ENV.every(k=>process.env[k])}
function headers(extra={}){return {apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}`,"Content-Type":"application/json",Prefer:"return=representation",...extra}}
function endpoint(table,query=""){return `${process.env.SUPABASE_URL}/rest/v1/${table}${query}`}
async function db(table,query="",init={}){const r=await fetch(endpoint(table,query),{...init,headers:{...headers(),...(init.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)throw new Error(body?.message||body?.hint||body?.details||`数据库请求失败：${table}`);return body}
function tokenFrom(req){return String(req.headers["x-mcj-service-token"]||"")}
function tokenSecret(){return process.env.SERVICE_SESSION_SECRET||process.env.SUPABASE_SERVICE_ROLE_KEY||"mcj-service-dev-secret"}
function signPayload(payload){return crypto.createHmac("sha256",tokenSecret()).update(payload).digest("base64url")}
function makeToken(staff){const payload=Buffer.from(JSON.stringify({id:staff.id||staff.uid,role:staff.role||"customer_service",at:Date.now()})).toString("base64url");return `${payload}.${signPayload(payload)}`}
function readToken(token){try{const [payload,sig]=String(token||"").split(".");if(!payload||!sig||sig!==signPayload(payload))return null;return JSON.parse(Buffer.from(payload,"base64url").toString("utf8"))}catch{return null}}
function hashPassword(password){return crypto.createHash("sha256").update(String(password)).digest("hex")}
function safeStaff(row={}){return {id:row.id||row.uid||row.staff_id,name:row.nickname||row.name||"客服",role:row.role||"customer_service",phone:row.phone||"",email:row.email||"",shift:row.shift||"",onlineStatus:row.online_status||"离线",clockedIn:!!row.clocked_in,avatar:row.avatar_url||"/assets/meow-cuijiao-brand.jpg",lastLogin:row.last_login_at||"",device:row.last_device||""}}
async function requireService(req){const token=readToken(tokenFrom(req));if(!token)throw Object.assign(new Error("未登录客服端"),{status:401});if(!SERVICE_ROLES.has(token.role))throw Object.assign(new Error("无权访问客服端"),{status:403});return token}
function emptyData(){return {staff:{},summary:{todayVisitors:0,pendingReplies:0,todayOrders:0,runningOrders:0,waitingBossConfirm:0,afterSales:0,completedToday:0,attendanceDays:0,myConversations:0},conversations:[],messages:[],orders:[],players:[],afterSales:[],attendance:{},salary:{},quickReplies:[],orderStatuses:ORDER_STATUSES,paymentStatuses:PAY_STATUSES}}
function normalizeConversation(row){return {id:row.id,name:row.name||row.customer_name||"老板",uid:row.uid||row.customer_uid||"",avatar:row.avatar||row.avatar_url||"/assets/meow-cuijiao-brand.jpg",lastMessage:row.last_message||"",lastTime:row.last_time||row.updated_at||"",unread:Number(row.unread_count||0),assignedService:row.assigned_service_name||row.assigned_service||"",onlineStatus:row.online_status||"离线",status:row.status||"待接入",category:row.category||row.status||"待接入",profile:row.profile||{}}}
function normalizeMessage(row){return {id:row.id,conversationId:row.conversation_id,senderRole:row.sender_role,type:row.type||"text",content:row.content||"",createdAt:row.created_at,readAt:row.read_at}}
function normalizeOrder(row){return {id:row.id||row.order_no,bossName:row.boss_name||row.customer_name||"",playerName:row.player_name||"",game:row.game||"",serviceContent:row.service_content||row.service||"",amount:Number(row.amount||row.paid_amount||0),orderStatus:row.order_status||row.status||"待支付",paymentStatus:row.payment_status||"未支付",serviceStaff:row.service_staff_name||row.customer_service_name||"",createdAt:row.created_at||""}}
function normalizePlayer(row){return {id:row.id||row.uid,name:row.nickname||row.name||"",level:row.level_name||row.level||"",game:row.main_game||row.game||"",price:row.price?`RM${row.price}/小时`:"",onlineStatus:row.online_status||"离线",workStatus:row.work_status||row.order_status||"暂停接单",runningOrders:Number(row.running_orders||0),rating:row.rating||"-"}}
function normalizeAfterSale(row){return {id:row.id,orderId:row.order_id,bossName:row.boss_name||"",playerName:row.player_name||"",type:row.type||row.reason_type||"",amount:Number(row.amount||0),status:row.status||"待处理",createdAt:row.created_at,serviceStaff:row.service_staff_name||""}}
async function bootstrap(staffId){const [staffRows,conversations,messages,orders,players,afterSales,attendanceRows,salaryRows,quickRows]=await Promise.all([
  db("customer_service_staff",`?id=eq.${encodeURIComponent(staffId)}&limit=1`),
  db("conversations","?order=updated_at.desc&limit=100"),
  db("messages","?order=created_at.asc&limit=300"),
  db("orders","?order=created_at.desc&limit=100"),
  db("players","?order=updated_at.desc&limit=100"),
  db("after_sales_cases","?order=created_at.desc&limit=100"),
  db("attendance_records",`?staff_id=eq.${encodeURIComponent(staffId)}&order=created_at.desc&limit=31`),
  db("salary_records",`?staff_id=eq.${encodeURIComponent(staffId)}&order=created_at.desc&limit=1`),
  db("quick_replies","?enabled=eq.true&order=sort.asc&limit=100")
]);
const data=emptyData();data.staff=safeStaff(staffRows[0]||{id:staffId});data.conversations=(conversations||[]).map(normalizeConversation);data.messages=(messages||[]).map(normalizeMessage);data.orders=(orders||[]).map(normalizeOrder);data.players=(players||[]).map(normalizePlayer);data.afterSales=(afterSales||[]).map(normalizeAfterSale);data.attendance={monthDays:(attendanceRows||[]).length,clockInAt:attendanceRows?.[0]?.clock_in_at||"",clockOutAt:attendanceRows?.[0]?.clock_out_at||"",workHours:attendanceRows?.[0]?.work_hours||0,lateCount:(attendanceRows||[]).filter(x=>x.status==="迟到").length,todayChats:0,todayCompleted:data.orders.filter(o=>o.orderStatus==="已完成").length};data.salary=salaryRows?.[0]||{};data.quickReplies=(quickRows||[]).map(x=>x.content||x.text).filter(Boolean);data.summary={todayVisitors:data.conversations.length,pendingReplies:data.conversations.filter(c=>c.unread>0).length,todayOrders:data.orders.length,runningOrders:data.orders.filter(o=>o.orderStatus==="进行中").length,waitingBossConfirm:data.orders.filter(o=>o.orderStatus==="待老板确认").length,afterSales:data.afterSales.filter(a=>a.status!=="已关闭").length,completedToday:data.orders.filter(o=>o.orderStatus==="已完成").length,attendanceDays:data.attendance.monthDays,myConversations:data.conversations.filter(c=>c.assignedService===data.staff.name).length};return data}
export default async function handler(req,res){try{const action=String(req.method==="GET"?req.query.action:req.body?.action||"");if(!hasDb())return json(res,req.method==="GET"?200:503,{ok:req.method==="GET",data:emptyData(),message:"未配置 SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY，客服端不返回模拟数据，操作也不会写入本地。",requiredTables:["customer_service_staff","conversations","conversation_members","messages","orders","order_assignments","players","bosses","after_sales_cases","attendance_records","salary_records","operation_logs"]});
if(action==="login"){const account=String(req.body?.account||"").trim();const password=String(req.body?.password||"");if(!account||!password)return json(res,400,{ok:false,message:"请输入客服账号和密码"});const rows=await db("customer_service_staff",`?or=(id.eq.${encodeURIComponent(account)},email.eq.${encodeURIComponent(account)},phone.eq.${encodeURIComponent(account)})&limit=1`);const staff=rows?.[0];if(!staff)return json(res,401,{ok:false,message:"客服账号不存在"});if(staff.status!=="启用")return json(res,403,{ok:false,message:"客服账号未启用或已冻结"});if(!SERVICE_ROLES.has(staff.role||"customer_service"))return json(res,403,{ok:false,message:"无权访问客服端"});if(!staff.password_hash)return json(res,403,{ok:false,message:"客服账号未配置密码，请联系管理员"});const passwordHash=hashPassword(password);if(staff.password_hash!==password&&staff.password_hash!==passwordHash)return json(res,401,{ok:false,message:"密码错误"});await db("customer_service_staff",`?id=eq.${encodeURIComponent(staff.id)}`,{method:"PATCH",body:JSON.stringify({last_login_at:new Date().toISOString(),online_status:"在线"})});return json(res,200,{ok:true,session:{token:makeToken(staff),user:safeStaff(staff)}})}
const service=await requireService(req);if(req.method==="GET"&&action==="bootstrap")return json(res,200,{ok:true,data:await bootstrap(service.id)});
if(req.method!=="POST")return json(res,405,{ok:false,message:"Method Not Allowed"});
if(action==="send_message"){const conversationId=String(req.body?.conversationId||"");const content=String(req.body?.content||"").trim();if(!conversationId||!content)return json(res,400,{ok:false,message:"缺少会话或消息内容"});await db("messages","",{method:"POST",body:JSON.stringify({conversation_id:conversationId,sender_id:service.id,sender_role:"service",type:"text",content,created_at:new Date().toISOString()})});await db("conversations",`?id=eq.${encodeURIComponent(conversationId)}`,{method:"PATCH",body:JSON.stringify({last_message:content,last_time:new Date().toISOString(),assigned_service:service.id,status:"我的会话"})});return json(res,200,{ok:true,message:"消息已发送"})}
if(action==="take_over"||action==="take_next"){const id=String(req.body?.conversationId||req.body?.id||"");const query=id?`?id=eq.${encodeURIComponent(id)}&limit=1`:"?status=eq.待接入&limit=1";const rows=await db("conversations",query);const c=rows?.[0];if(!c)return json(res,404,{ok:false,message:"没有可接入会话"});if(c.assigned_service&&c.assigned_service!==service.id)return json(res,409,{ok:false,message:"该会话已由其他客服接入"});await db("conversations",`?id=eq.${encodeURIComponent(c.id)}`,{method:"PATCH",body:JSON.stringify({assigned_service:service.id,status:"我的会话",updated_at:new Date().toISOString()})});return json(res,200,{ok:true,message:"会话已接入"})}
if(action==="end_conversation"){await db("conversations",`?id=eq.${encodeURIComponent(req.body?.conversationId||req.body?.id)}`,{method:"PATCH",body:JSON.stringify({status:"已结束",ended_at:new Date().toISOString()})});return json(res,200,{ok:true,message:"会话已结束"})}
if(action==="create_order"){const o=req.body?.order||{};const row={id:`CS-${Date.now()}`,boss_uid:o.boss,order_type:o.orderType,game:o.game,server:o.server,game_id:o.gameId,service_content:o.serviceContent,duration:o.duration,appointment_at:o.appointmentAt,amount:Number(o.amount||0),order_status:req.body?.mode==="draft"?"草稿":"待接单",payment_status:"未支付",customer_service_id:service.id,service_staff_name:service.id,created_at:new Date().toISOString()};await db("orders","",{method:"POST",body:JSON.stringify(row)});if(req.body?.conversationId)await db("messages","",{method:"POST",body:JSON.stringify({conversation_id:req.body.conversationId,sender_id:service.id,sender_role:"system",type:"order_card",content:`客服已创建订单 ${row.id}`,card_payload:row,created_at:new Date().toISOString()})});return json(res,200,{ok:true,message:req.body?.mode==="dispatch"?"订单已创建并准备发布抢单":"订单已创建",order:row})}
if(action==="publish_dispatch"||action==="assign_player"||action==="send_player_card")return json(res,501,{ok:false,message:"该操作需要连接 order_assignments 与陪玩端通知接口，当前未伪造成功"});
if(action==="after_sale_note"||action==="request_catfood_comp"||action==="blacklist_request")return json(res,501,{ok:false,message:"已进入受控流程，需接入管理员审核接口后执行"});
if(action==="clock_in"||action==="clock_out"){const today=new Date().toISOString().slice(0,10);const rows=await db("attendance_records",`?staff_id=eq.${encodeURIComponent(service.id)}&work_date=eq.${today}&limit=1`);if(action==="clock_in"){if(rows?.[0]?.clock_in_at)return json(res,400,{ok:false,message:"今天已经上班打卡"});await db("attendance_records","",{method:"POST",body:JSON.stringify({id:`ATT-${Date.now()}`,staff_id:service.id,work_date:today,clock_in_at:new Date().toISOString(),created_at:new Date().toISOString()})});return json(res,200,{ok:true,message:"上班打卡成功"})}if(!rows?.[0]?.clock_in_at)return json(res,400,{ok:false,message:"未上班不能下班打卡"});if(rows?.[0]?.clock_out_at)return json(res,400,{ok:false,message:"今天已经下班打卡"});await db("attendance_records",`?id=eq.${encodeURIComponent(rows[0].id)}`,{method:"PATCH",body:JSON.stringify({clock_out_at:new Date().toISOString()})});return json(res,200,{ok:true,message:"下班打卡成功"})}
return json(res,400,{ok:false,message:"未知客服端操作"})}catch(e){return json(res,e.status||500,{ok:false,message:e.message||"客服端接口异常"})}}

